### ISSUE TITLE
Error in translation 

### ISSUE THREAD

**Issue by RealPasso** [dotnet/dotnet-api-docs.fr-fr#1]
RunContinuationsAsynchronously	64	
Indique que la tâche de continuation doit être exécutée de façon synchrone &lt;= should be ASYNCHRONE.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 782caa8b-fdef-0d92-33b7-6d9b081a125c
* Version Independent ID: 36dfe096-6b39-4ca4-262a-3fbd6dd14a1c
* Content: [TaskContinuationOptions Enum (System.Threading.Tasks)](https://docs.microsoft.com/fr-ca/dotnet/api/system.threading.tasks.taskcontinuationoptions?view=netframework-4.7.2)
* Content Source: [xml/System.Threading.Tasks/TaskContinuationOptions.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Threading.Tasks/TaskContinuationOptions.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Bonjour, @RealPasso 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
Bonjour, @RealPasso

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-ca/dotnet/api/system.threading.tasks.taskcontinuationoptions?view=netframework-4.7.2 du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
