### ISSUE TITLE
l’avantage de qualité 

### ISSUE THREAD

**Issue by vaydi08** [dotnet/dotnet-api-docs.fr-fr#2]
pouvez vous m'expliquer l'avantage de Quality,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 501eef73-858d-346d-8c72-3128f59f4f95
* Version Independent ID: 8fabd8b0-d680-742c-4fcc-909299d36891
* Content: [StringWithQualityHeaderValue Class (System.Net.Http.Headers)](https://docs.microsoft.com/fr-fr/dotnet/api/system.net.http.headers.stringwithqualityheadervalue?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Http.Headers/StringWithQualityHeaderValue.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Net.Http.Headers/StringWithQualityHeaderValue.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Bonjour @vaydi08 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
