### ISSUE TITLE
La traduction par l'automate n'est pas idéale

### ISSUE THREAD

**Issue by Tecknoth** [dotnet/dotnet-api-docs.fr-fr#4]
Certaines tournures de phrase doivent être corrigées, par endroit l'ordre des mots n'est pas bon non plus.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0f3e8dd0-82b1-8e21-6fbb-033414bcafc8
* Version Independent ID: 521fdf12-14b6-37c9-a964-e3c2fb8cd059
* Content: [Application.ThreadException Event (System.Windows.Forms)](https://docs.microsoft.com/fr-fr/dotnet/api/system.windows.forms.application.threadexception?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Windows.Forms/Application.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Windows.Forms/Application.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Bonjour @Tecknoth 

Merci pour votre feedback. La page en question a été traduite automatiquement, ce qui ne permet pas toujours une bonne compréhension. Nous avons récemment ajouté l’option « Lire en anglais » (sur la droite) qui permet de lire la version anglaise sans avoir à modifier les paramètres de langue. 
Cordialement, 

L’équipe Microsoft DOCS International

**Comment by Tecknoth** [comment]
Bonjour,

Merci pour votre réponse. Parallèlement à mon commentaire j'ai créé une contribution sur github en proposant une modification de la documentation. Y a-t-il une chance pour que cette contribution soit prise en compte ?

Jean-Yves Besserer

________________________________

**Comment by CeciAc** [comment]
Oui, c'est la procédure correcte pour ces suggestions.
