### ISSUE TITLE
FDpelletsgitinfos

### ISSUE THREAD

**Issue by FDpellets** [dotnet/dotnet-api-docs.fr-fr#5]
[infos utiles]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5bf4fc94-6684-b355-5b27-c348a876baff
* Version Independent ID: 589682e8-7d87-0303-6962-677f8f547081
* Content: [ConfigurationBuilderCollection Class (System.Configuration)](https://docs.microsoft.com/fr-fr/dotnet/api/system.configuration.configurationbuildercollection?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/ConfigurationBuilderCollection.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Configuration/ConfigurationBuilderCollection.xml)
* Product: **dotnet-api**
* Technology: **system.configuration**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Bonjour @FDpellets 

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes. 
Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
