### ISSUE TITLE
PemEncodeSigningRequest example is not properly formatted

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/dotnet-api-docs.fr-fr#6]
On the english page, the markdown code fences are shown, and the language is not detected as C#.

Could you please fix that?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6492c5e5-e154-6ead-e9f4-ea11a87fb29d
* Version Independent ID: 504f60e9-45e5-70ad-0bb6-d25da199efb6
* Content: [CertificateRequest.CreateSigningRequest Method (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/fr-fr/dotnet/api/system.security.cryptography.x509certificates.certificaterequest.createsigningrequest?view=netframework-4.8)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2438](https://github.com/dotnet/dotnet-api-docs/issues/2438) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @jeremyVignelles

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2438

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by jeremyVignelles** [comment]
I have already been notified, thanks 👍.
Side note: I'm french, so I will always go to the fr-fr site, but I'm always browsing with the english version. When I submitted the report, I expected my report to go on the original doc bug tracker instead of this one.

Other weird thing, I don't see the feedbacks and comments on the en-US site, is that normal?
