### ISSUE TITLE
Manque d'exemples

### ISSUE THREAD

**Issue by eskivor** [dotnet/dotnet-api-docs.fr-fr#8]
Il manque beaucoup d'informations, notamment quel est le résultat attendu

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 48e1abb6-6602-9ed2-2d6f-ae4e43d43f14
* Version Independent ID: a0696694-2c26-e625-1bef-e0d2240ddf86
* Content: [Math.MaxMagnitude(Double, Double) Method (System)](https://docs.microsoft.com/fr-fr/dotnet/api/system.math.maxmagnitude?view=netcore-3.0&viewFallbackFrom=netframework-4.8#feedback)
* Content Source: [xml/System/Math.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System/Math.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2577](https://github.com/dotnet/dotnet-api-docs/issues/2577) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Bonjour @eskivor 

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/dotnet/dotnet-api-docs/issues/2577

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
